-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('OWNER', 'ADMINISTRATOR', 'MANAGER', 'STAFF', 'CUSTOMER', 'USER', 'SUBSCRIBER');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "role" "UserRole" NOT NULL DEFAULT 'CUSTOMER';
